[server]
port = 8501
address = "0.0.0.0"
headless = true
runOnSave = false
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 8501

[client]
showErrorDetails = "full"
toolbarMode = "minimal"