[server]
port = 8080
address = "0.0.0.0"
headless = true
runOnSave = false
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 8080

[client]
showErrorDetails = "full"
toolbarMode = "minimal"