name: Build & Deploy (Full Stack)

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_WORKING_DIR: './infra'
  ECR_REPO_NAME: 'fraud-detection-system'
  ECR_FRONTEND_REPO_NAME: 'fraud-detection-frontend'

jobs:
  deploy-process:
    name: "Infra -> Build -> Deploy"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply (ECR Only)
        run: terraform apply -auto-approve -input=false -target=aws_ecr_repository.repo
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          TF_VAR_langsmith_api_key: ${{ secrets.LANGSMITH_API_KEY }}
          TF_VAR_langsmith_project: ${{ secrets.LANGSMITH_PROJECT }}
          TF_VAR_langchain_tracing_v2: ${{ secrets.LANGCHAIN_TRACING_V2 }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          REPO_NAME=${{ env.ECR_REPO_NAME }}
          
          echo "Construyendo imagen backend..."
          docker build -t $ECR_REGISTRY/$REPO_NAME:latest -f src/backend/Dockerfile .
          
          echo "Subiendo imagen backend..."
          docker push $ECR_REGISTRY/$REPO_NAME:latest
      
      - name: Build & Push Frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          REPO_NAME=${{ env.ECR_FRONTEND_REPO_NAME }}

          echo "Construyendo imagen frontend..."
          docker build -t $ECR_REGISTRY/$REPO_NAME:latest -f src/frontend/Dockerfile .
          
          echo "Subiendo imagen frontend..."
          docker push $ECR_REGISTRY/$REPO_NAME:latest

      - name: Terraform Apply (Full Infra)
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          TF_VAR_langsmith_api_key: ${{ secrets.LANGSMITH_API_KEY }}
          TF_VAR_langsmith_project: ${{ secrets.LANGSMITH_PROJECT }}
          TF_VAR_langchain_tracing_v2: ${{ secrets.LANGCHAIN_TRACING_V2 }}